### ISSUE TITLE
Convert Vision Documents into initial static site

### ISSUE THREAD

**Issue by b5** [datatogether/datatogether#1]
Hey team,

We should get initial drafts of vision docs in markdown into here. We can use this to build a static site to display docs.

**Comment by mhucka** [comment]
Sorry to be dense, but can you elaborate a little bit more about the kind of static site you mean? I'm confused about whether you mean a kind of landing page/project description site (e.g., like the IPFS home page https://ipfs.io) or a static mock-up of the envisioned Data Together system, or something else.

Relatedly, I'd be willing to try to collect documents, as a learning exercise, and pull them together in here.

**Comment by b5** [comment]
haha definitely not dense! I'm thinking more "site copy" that explains the data together model from a conceptual perspective, so yes I was thinking very much along the lines of the ipfs home page.

But I do want to leave some room for interpretation of what should & shouldn't be in there. The main point of this repo is get something that complies to a static site that introduces the Data Together model. That might include technical details, maybe not, either way I think we should start small :)

**Comment by dcwalk** [comment]
hopping on this issue as well to ask about the name of the repo. I'm a little confused about the scope of these docs... I thought there was a docs repo somewhere when it was in archivers.space? Did it get moved over/folded into something else?

**Comment by b5** [comment]
I named the repo based on the convention specified by [github's pages](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages) to have the url of the site be `datatogether.github.io`. Totally open to a name change / move if it's confusing.

Old repo is still up, it's here: https://github.com/archivers-space/docs I didn't move it over b/c I'm trying to figure out how showing data together _concepts_ do/don't mesh with data together _technical documentation_. I personally think this repo should hold concepts contained within the vision documents we're working on in google docs, illustrated with technical examples & callouts, but again, am open to others rethinking any of this. Up to and including just deleting this repo outright :)

**Comment by dcwalk** [comment]
Thanks for the links, fair point about the concept v. technical documentation! I'll reticket merging into this repo eventually for discussion :)

Unless my brain is totally fried from the sun I think the repo actually has to be `datatogether.github.io` if you want to serve over gh-pages?

**Comment by b5** [comment]
lololol you might be right. If so feel free to rename the repo to do that. Apparently I'm as bad at reading documentation as I am at writing it :)

**Comment by titaniumbones** [comment]
in today's (7/13/2017) call we discussed using a single site to house both the technical docs and the vision/etc. docs intended for a more general audience.  The thought is to just use said structure temporarily in advance of hackathons next week, and maybe restructure on the basis of more thorough thinking-through soon.

**Comment by dcwalk** [comment]
I'm going to suggest we consider [hugo](https://gohugo.io/) for our static-site generator. @titaniumbones has been using it recently for other purposes and it might be fun to stick to golang across the repos...? 

(tho obviously we have a strong capacity with jekyll)

**Comment by mhucka** [comment]
Hugo looks pretty nice!

**Comment by flyingzumwalt** [comment]
IPFS team switched from jekyll to hugo sometime last year for all of our sites. The switch was easy and we are very happy with hugo. Perk: hugo's default settings produce sites that are easier to publish directly over IPFS (all relative links)

**Comment by b5** [comment]
awww let's be sure to let @spf13 know that y'all are into Hugo. Steve's a very nice human.

**Comment by titaniumbones** [comment]
@flyingzumwalt do you guys have a simple theme we could use to set the site up? I am wading into Hugo but, in htis as in so many things, I'm pretty slow.

If we're ready to do so I can move the Vision Docs to a GH repo tonight, and put an initial ocnfig file in place. But I'm slow with design.

**Comment by flyingzumwalt** [comment]
Best reference I can offer is the source code for our sites. I'm pretty sure they're all using hugo now.
- https://github.com/ipfs/website
- https://github.com/libp2p/website
- https://github.com/ipld/website
- https://github.com/multiformats/website

I will be working on the vision docs tonight. Is it inconvenient to wait until tomorrow to move them?

**Comment by titaniumbones** [comment]
@flyingzumwalt fine to wait till tomorrow. I may run out of time -- crazy weekend followed by crazy week.  but would like to help.

**Comment by titaniumbones** [comment]
I like ipfs.io, and i think a single-page layout will work for our vision stuff, so if it's OK I will start from there.  More familiar w/ sass than less but I'm sure I can more or less work it out.  Hoping @dcwalk can find time to help too.  Maybe @shaqsingh also?

**Comment by titaniumbones** [comment]
though on reflection if you want to make some crazy svg animations like [this one](http://ipld.io/) please go right ahead.

**Comment by flyingzumwalt** [comment]
We can probably get the people who made those animations (I like the one on libp2p.io) to come through and add animations over the next few weeks. It will be great to ship something static in the meantime.

**Comment by titaniumbones** [comment]
Based on b5's comments in slack I spent my Friday otherwise, which is
probably just as well since I'm likely about 0.5% as efficient as most
of the other people on this isuse when it comes to these things.

I will be looking at the vision docs i advance of my brief talk on
Thursday. @flyingzumwalt do you have any visuals I shouild pilfer from?
I will have only a very brief time to present.

**Comment by flyingzumwalt** [comment]
@titaniumbones I haven't had a chance to create new visuals yet. Attaching a draft of my slides for the ESIP talk. It's basically an updated version of the Code4Lib talk.
[Data Together - ESIP Summer Meeting July 2017.pdf](https://github.com/datatogether/datatogether/files/1171166/Data.Together.-.ESIP.Summer.Meeting.July.2017.pdf)

**Comment by dcwalk** [comment]
Hey! so we have a website, it reflects many of the details in here, but more importantly NY crew during the doc sprint wound up doing a more thorough re-think of website content and sitemap.

I'm going a bit on a limb here, but I'm going to _close this issue_ as no longer needed, please feel free to re-open if you feel like it needs to be open still!
