### ISSUE TITLE
Add drafts to vision & principles doc

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#13]
We discussed at the [partnership meeting Aug 29](https://docs.google.com/document/d/1Lb0QARibJ-McBIy6EHeYcffgyiF6XImp-OrQHPGc9fs/edit#) and decided to set a deadline to submit various draft vision and principles/values

**Comment by ebarry** [comment]
at the time of last week's Tuesday meeting, we set August 31 as the deadline for folks to send in drafts. Please paste any docs that i should be pulling from here, folks!

**Comment by dcwalk** [comment]
This happened (sorta :)
