### ISSUE TITLE
Consolidate first draft of vision & principles doc

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#14]
We discussed at the [partnership meeting Aug 29](https://docs.google.com/document/d/1Lb0QARibJ-McBIy6EHeYcffgyiF6XImp-OrQHPGc9fs/edit#) and decided--

@ebarry is going to pull together the various draft vision and principles/values from #13 in preparation for our meeting covered by #15

**Comment by dcwalk** [comment]
From convo on Sept 8:

The document structure is moving towards:

> **Vision** -- describe future abilities (NOT describing a utopian state). Meant to be Inspirational to ourselves + our future partners to strive together, can be more flowery. 
> 
> [if needed, problem statement / historical context -- @flyingzumwalt able to take a pass at consolidating, then Liz to edit]
> 
> Mission (should be 1 sentence! But we’ll probably start with a couple/few sentences. Liz take a pass at)
> 
> [if needed, model: strategy / strategic plan / strategic initiatives if there’s rollover on “how” we do our work that doesn’t fit into the mission]
> 
> Values -- single words with short sentence fragment descriptions  (@dcwalk to consolidate, Liz to edit)
> 
> [if needed, elevator pitches -- the “all-in-one” sentences that efficiently go from the problem to the solution. Matt, all, to contribute elevator pitches]

[Working doc](https://docs.google.com/document/d/1MOaOtEJWLFqUmqMtF5ytjaey3QXZ5VSbj2LN0c1np0I/edit?)

**Comment by dcwalk** [comment]
After the meeting on Sept 8, @ebarry was going to do another pass structuring/organizing the doc (:tada:) mid-Sept

**Comment by dcwalk** [comment]
Hey @ebarry -- I forget the timeline you were thinking on for this, are you able to remind me? 😟

**Comment by ebarry** [comment]
Hi @dcwalk, I am working on it in this week!

--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by dcwalk** [comment]
This happened! This was merged in #23, with second iteration convos in #24 and #25!
I'm closing for now as we have another issue to track next phase feedback
