### ISSUE TITLE
Research examples of distributed/federated identification

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#20]
Copied from https://github.com/datatogether/roadmap/issues/25#issue-250075811:

@b5:
> Data Together needs methods for users to identify themselves in a distributed system. There are lots of examples of this in the wild, let's collect them up here before diving in on how to approach this feature

@dcwalk (hey that's me 😉 ):
> Just some examples from social / chat for now :
> 
> - [XMPP](https://en.wikipedia.org/wiki/XMPP) / Jabber 
> - [Ricochet](https://ricochet.im/)
> - [Matrix.org](https://matrix.org/) on github: https://github.com/matrix-org
> - [Mastadon](https://joinmastodon.org/) / [GNU Social](https://gnu.io/)
> - [Secure Scuttle Butt](http://scuttlebot.io/) / [Patchwork](https://github.com/ssbc/patchwork)

**Comment by dcwalk** [comment]
Blockstack - https://blockstack.org/

**Comment by dcwalk** [comment]
I'm closing this here as I don't think we've found a way to think about how or why we'd undertake this research at this juncture!

**Comment by jackjamieson2** [comment]
Just saw that you closed this — perfect time to chime in with another example :)



[Indieweb.org/indieauth](https://indieweb.org/IndieAuth) —  
> "IndieAuth is a way for doing Web sign-in, where you use your own homepage to sign in to other places.
> 
> IndieAuth was build on ideas and technology from existing proven technologies like OAuth and OpenID but aims at making it easier for users as well as developers. It also decentralises much of the process so completely separate implementations and services can be used for each part.



Spec: https://indieauth.spec.indieweb.org/
Example implementation - https://indieauth.com/
