### ISSUE TITLE
Decide how to spend our small amount of event-related funding

### ISSUE THREAD

**Issue by titaniumbones** [datatogether/datatogether#22]
We have a small amount of money for datatogether events. Since our events structure has shifted, how should we spend the money?

*Proposal 1:* buy pizza and/or coffee for a bunch of small groups, e.g. DR Boston, others.  
*Proposal 2:* ??

Let's use this issue to figure out a strategy. Not because it's so much money, but because it's an opportunity to get more specific/thoughtful about the new strategy.

**Comment by shapironick** [comment]
There are a lot of expenses that we are waiting to hear back from. it looks like there is at a minimum $1,300 to be spent before Oct 31st. It could be over $2,000? 

- Interviews looks to be 900 under budget.
- Food for the 4s event is looking to be several hundred dollars under budget. 
- Matt's SAA trip was a couple hundred dollars under budget. 

I'll report back when I've gotten responses.

**Comment by dcwalk** [comment]
_Proposal 2: Pay someone to consult/assist with set up on a new event toolkit?_ (would this be a nightmare??)
_Proposal 2a: Buy coffee/pizza/vegan snacks for a doc sprint last 2 weeks of Oct_ <-- this is in line with the roadmap timeline we discussed on the DT stand up on Thursday

**Comment by shapironick** [comment]
I crunched some numbers! DT should have $1,418 to spend on this jump starting. This is assuming that the interviewers spend all of their 1k, which they have told me they would (so far they are 850ish short). Everything else in the calculations are now firm.

**Comment by shapironick** [comment]
+1 on proposal 1 and 2a (i'm scared of 2)

**Comment by dcwalk** [comment]
Okay, we've got a plan: 
- Host a 2 day sprint before the end of October, on *Thurs, Fri 26-27*
- Focus is docs, test coverage badges, and website serving 
- Money would go to sending food to people working on it (NY, Toronto, Boston??) and stickers :tada:
- Along with @mattprice (and possibly @patcon), Toronto can commit to having 16hr coverage on those days of someone working out of the TRU!
- Main goal is to ease handoffs with code, bring Protocol people up to speed, and think ahead to enticing tech people to the project.

**Comment by dcwalk** [comment]
I'm going to close this for now, and we can share a budget tonight to EDGI `#funding` and `#bookkeeping`
