### ISSUE TITLE
Host 2-day Sprint for Data Together on Oct 26-27

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#26]
Join our 🚀📔 **Two-day Data Together Sprint, Oct 26-27** 🚀📔  ([Blog post](https://envirodatagov.org/data-together-sprint/))

---
On Thursday and Friday next week, [**Data Together**](http://datatogether.org/) is hosting a two-day sprint to come together and improve project documentation, update our website content, and create project and test coverage guidelines. We'll supply coffee, lunch, and stickers for all attendees. ☕

---
**[CHECK OUT OUR SPRINT PAD](https://hackmd.io/s/HyZIqVnab#) for important links and notes**
---

What: Our project helps communities steward the data they care about, through acting as the civic layer of the decentralized web. Help us spruce up overall project documentation, begin to identify our test coverage, and update our website content and deployment!
When: **Thursday and Friday, Oct 26-27**, 9:00 - 18:00 ET 🕘 
Where: This event is in-person in **Toronto, Brooklyn, and Boston** and online at [github.com/datatogether](https://github.com/datatogether/datatogether/) and [`#datatogether` on archivers.slack.com](https://archivers-slack.herokuapp.com/)!
Who: All are welcome! This is a collaborative event with no experience of Data Together required, you can join us remotely and for all or only part of the days! 

Please [RSVP by form](https://goo.gl/forms/sddgFj5JoAwRFhyQ2) so we can send sprint details on Wednesday: https://goo.gl/forms/sddgFj5JoAwRFhyQ2

| Toronto  | Brooklyn  | Boston  |
|---|---|---|
| **Technoscience Research Unit**<br />Room 7020, Robarts Library<br />130 St. George Street  | **WeWork Dumbo Heights**<br />Boardroom 6A, Sands Building<br />81 Prospect Street<br /> | **MIT Campus**<br />Room 4-253, Building 4<br />182 Memorial Drive |
| [📍Robarts directions](http://semaphore.utoronto.ca/contact.php) | [📍WeWork directions](https://goo.gl/maps/irb8sSFQ4bH2) | [📍Building 4 directions](http://whereis.mit.edu/?go=4) |
| Take the **P4 elevator**, reached via the 2nd floor of Robarts to the 7th floor, follow signs to Semaphore Lab | Guests need photo ID, ask for Brendan O'Brien, qri.io in the lobby | Public building with floor and elevator access to the second floor |

---
**Next Steps**:

- Planning is mostly done, you can see our [Trello planning board](https://trello.com/b/XCIPxIWu/data-together-oct-26-27-sprint-planning)
- [Draft participant email](https://hackmd.io/IYDgrADAjFCmIFoAsSxmQTgrBAjMGATAgCYDGZA7CQGyyVIiWxA=?view#)
- [**Sprint Doc Pad**](https://hackmd.io/s/HyZIqVnab#)
---
**Sprint Goals** (discussed Thursday, Oct 19):

1. Improve **Documentation**
1. Initial **Testing** Coverage
1. Update datatogether.org **Website**
1. Create **"First Time" User** Issues (_stretch_)
1. Establish Technical Documentation **Guidelines** (_stretch_)

We have our [**Sprint Milestone**](https://github.com/datatogether/roadmap/milestone/3) where tasks falling under these goals are documented!

**Comment by dcwalk** [comment]
Hey crew! I've set up a Sprint Planning Board just to make sure we don't miss small (or large) planning details:

https://trello.com/b/XCIPxIWu/data-together-oct-26-27-sprint-planning

**Comment by flyingzumwalt** [comment]
FYI over the coming weeks I will be working to assemble and document user journeys around some of the use cases around Data Together. I know this won't fit in the schedule for this week, but please keep it in mind and let me know if you are interested in contributing to those documents. More info: https://github.com/ipfs/pm/issues/515

**Comment by dcwalk** [comment]
we did it!
