### ISSUE TITLE
Be explicit in repo description about where to start

### ISSUE THREAD

**Issue by patcon** [datatogether/datatogether#27]
roadmap and datatogether docs feels just a little ambiguous. Assuming that this repo is the right place, can we add something like this to the repo description?

```
Data Together Docs: :checkered_flag: START HERE :car::racehorse: 
```
> Data Together Docs: :checkered_flag: START HERE :car::racehorse:

**Comment by dcwalk** [comment]
That happened! I'm closing this :)
