### ISSUE TITLE
Add README and Templates

### ISSUE THREAD

**Issue by titaniumbones** [datatogether/datatogether#30]
Make sure this repo has the following files:
- [x] Readme `README.md`
   - [x] Has readme
   - [x] Repo Badges for: Github Project, Slack
   - [x] 1-3 sentence description of repository contents
   - [x] Getting Involved section
- [x] `LICENSE`
- [x] Org-wide Contributing Guidelines and Code of Conduct
- ~Issue Template -- `.github/ISSUE_TEMPLATE.md`~
- [x] GitHub Description from 1-3 sentence readme blurb

This issue forms part of [a project-wide meta-issue](https://github.com/datatogether/roadmap/issues/37)

**Comment by dcwalk** [comment]
This one is a little different because it is our main repo :) I've updated the checklist accordingly
