### ISSUE TITLE
Add definitions/descriptions of Activities to model.md

### ISSUE THREAD

**Issue by flyingzumwalt** [datatogether/datatogether#42]
withdrew this text from PR #41 because it's incomplete. Among other things needed here, @dcwalk flagged the need to draw language from radical/grassroots archival and library practice, and probably to add explicit references to them.

```
## Activities

### Decentralizing Data: Taking Possession of the Data you Rely On

### Coordinating to Possess Data Together

Applying a Participatory form of Library Practice
- Accessioning & Cataloging
- Collection Management -- Access, Discovery and Preservation services
```

**Comment by dcwalk** [comment]
As we've moved away from this framing I am going do close this issue for now as `wontdo`, if you believe this should be re-opened please feel free!
