### ISSUE TITLE
Add datatogether to up-for-grabs.net

### ISSUE THREAD

**Issue by patcon** [datatogether/datatogether#44]
https://github.com/up-for-grabs/up-for-grabs.net#add-a-project

They suggest the label "up-for-grabs", but I feel that "first-timers-only" communicates intention much more clearly (that we really only want new people working on these issues)

What place do we want to link to as the single project-wide link?
https://github.com/datatogether/datatogether#readme ?

As part of this, adding "Start here." to the repo description, to be:

> :balloon: Start here. Discussion for Data Together: Community Patterns for the Decentralized Web

# To Do

- [x] create pull request on up-for-grabs.net
- [x] ensure we are using `first-timers-only` as label across repos
  (@dcwalk reviewed 2018-03-14, have not cone probot/config style for labels but we should consider as project matures!)
- [x] update docs
  - [x] mention how we use first-timers-only. point to up-for-grabs.net in https://github.com/datatogether/datatogether `README`
  - [x] mention in https://github.com/datatogether/roadmap `README`
  - [x] update https://github.com/datatogether/roadmap **project guidelines**

**Comment by patcon** [comment]
https://archivers.co/ vs https://datatogether.org/

which is the better link? seeing it in readme, and they don't seem the same

**Comment by ebenp** [comment]
Cool!

**Comment by dcwalk** [comment]
@patcon-- I'm thinking we might want to move this issue to the roadmap repo, would that work for you? Just thinking this is more development focused (though we should trouble that in our "first-timer"/"up-for-grabs" labelling ;)

**Comment by dcwalk** [comment]
https://github.com/issues?q=is:open+org:datatogether+label:first-timers-only
and 
http://up-for-grabs.net/#/names/data%20together

are the helpful links 👍

**Comment by dcwalk** [comment]
@patcon could I get your take on whether the proposed revisions are a good first pass on integrating this?

**Comment by patcon** [comment]
They look great! Occupied today, but would love to jump on those over weekend :)

**Comment by dcwalk** [comment]
Okay, went ahead and merged. I think the only thing left is updating the project guidelines: https://github.com/datatogether/roadmap/pull/84

**Comment by dcwalk** [comment]
I'm calling this done for now, given the fact I've merged in the lingering issue, if we wanna create further issues lets do so in https://github.com/datatogether/roadmap/
