### ISSUE TITLE
Adopt defined pattern of Google Drive usage

### ISSUE THREAD

**Issue by patcon** [datatogether/datatogether#46]
Recognizing:
- the need for keeping private off-camera notes for sensitive meeting comments (like in the [2018 kick-off meeting](https://hackmd.io/s/HyrPT8ZNz)), and
- the need for clarity on where private things live, what exists, and how to gain access

I propose we adopt the two patterns as described here:
- [Working Open pattern: Google Drive folder hierarchy](https://hackmd.io/c/rynF_9jZz/https%3A%2F%2Fhackmd.io%2Fs%2FS12M4csbz)
  - slight modification: use "Non-Public" instead of "Privileged" to better communicate that those with access are not yet a special well-defined group, but rather just "participants who were welcome on a call" (this will need future consideration)
- [Working Open pattern: Private Resource Inventory](https://hackmd.io/c/rynF_9jZz/https%3A%2F%2Fhackmd.io%2Fs%2FSJYcCH_fG)

Inspirations:
- Enspiral is a loose worker cooperative aspiring to work and share resources differently. They have a [People Agreement](https://handbook.enspiral.com/agreements/people.html), which aims for a minimal hierarchy of 2 levels: "Contributors" (trusted by one "member") and "Members" (trusted by ALL members). The pattern above is trying to stay compatible with that way of operating, as I hope to propose we consider at a future time :) (There's no need to talk about this bullet in this issue, but happy to have convo later.)

cc: @flyingzumwalt

**Comment by dcwalk** [comment]
I think we are happy to move forward with this for now @patcon, I've gone through and done a quick clean of the public and non-public folders. 

Are we able to close this issue as done for now?

**Comment by dcwalk** [comment]
Just chatted with @patcon and it looks like we're okay to close this issue for now (correct me if I'm wrong!) and then issue and refine as needed/pain points arise
