### ISSUE TITLE
Roundtable: How do we see datatogether.org being used? 2018-Mar-19

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#51]
# Post Call

- @b5: Establish Shared (automated) deployment process https://github.com/datatogether/website/issues/11 https://github.com/datatogether/website/issues/30
- [x] @rgardaphe and @weatherpattern: shared/commentable wireframe using Zeplin https://github.com/datatogether/website/issues/32
- Identify Resource & Capacity Commitments for handling the engagement funnel by next coordinating meeting (6 weeks)
 
# Intro

We have a reasonable workflow for updating [datatogether.org](https://datatogether.org/) and during our October Sprint we identified [some milestones](https://github.com/datatogether/roadmap/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+website). @rgardaphe, @flyingzumwalt and @ebarry did some initial work on copy but it never made it to the website. How do people see us using our website? Can we prioritize certain content to add/develop?

Willing to Host: @rgardaphe 
Preparation:
  - Review latest wireframes: [Data Together Wireframes Home_v5.pdf](https://github.com/datatogether/datatogether/files/1813049/DT.Home_v5.pdf) (outcomes from October Doc sprint)

Call notes: https://docs.google.com/document/d/1GMSHYFYN4NRVvLdUmgFWmYa2Kny2vdRTitc3Ixu2woU/edit#

🙋🏻‍♀️ _what are [**weekly roundtables**](https://github.com/datatogether/datatogether/blob/master/guidelines/roundtable.md) anyway? They are discussions of a Data Together-related topic, challenge, or question led by a rotating facilitator. If you are hosting, be sure to check out [**how to host**](https://github.com/datatogether/datatogether/blob/master/guidelines/roundtable.md#how-to-host) (and add any improvements!)_

# Call Notes

- [**Wireframes**](https://github.com/datatogether/datatogether/files/1813049/DT.Home_v5.pdf)!
- Communicate Mission, Vision, & Values
  - Route visitors to content that allows them to:
    1. Learn more about Data Together itself
    2. Testimonials / examples of communities working alongside Data Together to gain a benefit
    3. “Signing up” or in other words, demonstrating an interest in connecting with DT ‘in real life’ whether they are technically savvy or not.
  - Idea: receive updates via a newsletter or something,
  - Idea: contribute to the codebase    
  - Endorse / Partner with Data Together
    - Explain what it means to ‘endorse’ Data Together and/or partner with us to drive a benefit from them, AND give them a mechanism to register their interest in doing so
    - Explain the founding story / raison d’etre, and the “Team/Contributors”:
    - Align on a format for sharing information on DT’s key contributors and leaders
- Revisit organization (information architecture)
  - Based on discussion of content, let’s align on some ideas for what goes on main page, etc.  WHAT goes WHERE and links to WHAT ELSE.
- Is archivers.co (website) going to be subsumed by datatogether.org?
  - We’d talked about this during Sprint, pulled most content removed from archivers.co ([https://github.com/datatogether/webapp](https://github.com/datatogether/webapp)) but need to check on status
- Is qri the backbone of Data Together? Or a separate tool? (Learning repo? How is it related to qri workflow? (or adding stuff to IPFS))
  - qri as implementing DT principles, but not an "only choice" and the learning repo is for DT codebase    
  - b5: qri is separate and has own docs, provenance tutorials and demos not in learning repo; learning repo is focused on data blobs
- Looking at wireframe, What are our key resources? Engagement funnel? Are there more strategies?
  - wireframes does well for where we are, what we are doing so far, contributors “more in touch”, interest in participating in
- data sets more than website archiving within scope? Is that still an open question?
  - Archivers a response to a potential loss, brought into contact with technologists and technologies, Umbrella of Data Together potentially enormous, partner vision similarly, productive tension and conflict, positions within. Out of the giant set of questions and potential trajectories, could prioritize an immediate set of questions, anchor or make concrete how we talk about community: “What is the next largest circle we could expand to” (most immediate vs. most broad)
- How are changes to the website deployed?
  - Currently asking @b5, moving to IPFS infra for automated deploys to IPFS with Jenkins
- How do we feel about pushing open the engagement funnel? (expressing interest section of wireframe) Without onboarding what are people engaged with?
  - Need a more explicit links to connect to where we have discussions! (Github, Our Calendar, Twitter etc…!)

**Comment by rgardaphe** [comment]
I'd be happy to facilitate!  I've attached the latest version of the mock-up I had made a few months back here, so everyone can take a look. I'll send @dcwalk a few bullets summarizing whatever I have related to notes taken re: the website as well. 


[DT Home_v5.pdf](https://github.com/datatogether/datatogether/files/1813049/DT.Home_v5.pdf)

**Comment by dcwalk** [comment]
yesssssss @rgardaphe! I hope you are able to edit my issue directly and add the points (and please do!). If not wanna just drop this in this issue?

**Comment by rgardaphe** [comment]
Hey @dcwalk  - I just sketched up a draft agenda on the [Data Together Roundtable Running Notes](https://docs.google.com/document/d/1GMSHYFYN4NRVvLdUmgFWmYa2Kny2vdRTitc3Ixu2woU/edit#heading=h.t7yl1uz930eo) google doc in green text. I wasn't able to edit the issue directly.  Lemme know if there's a better way to share/present this info (and if I should trim away the text wall I dropped in there).

**Comment by dcwalk** [comment]
Looks great @rgardaphe! 🎉 So stoked :))

**Comment by dcwalk** [comment]
Closing because this happened and TODOs are mentioned in https://github.com/datatogether/website
