### ISSUE TITLE
Roundtable: How do we see the distinction between web archiving or data sets for Data Together? 2018-Apr-16

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#60]
At the [How do we see datatogether.org being used? 2018-Mar-19 Roundtable](https://github.com/datatogether/datatogether/issues/51) an open question was surfaced about how or whether data sets and web archiving were understood to be "in scope": 

> Archivers a response to a potential loss, brought into contact with technologists and technologies, Umbrella of Data Together potentially enormous, partner vision similarly, productive tension and conflict, positions within.

Willing to Host: @jessogden  
Preparation: 

[identify any todos, links, helpful resources that people should check out]  

Call notes: https://docs.google.com/document/d/1GMSHYFYN4NRVvLdUmgFWmYa2Kny2vdRTitc3Ixu2woU/edit# 

🙋🏻‍♀️ _what are [**weekly roundtables**](https://github.com/datatogether/datatogether/blob/master/guidelines/roundtable.md) anyway? They are discussions of a Data Together-related topic, challenge, or question led by a rotating facilitator. If you are hosting, be sure to check out [**how to host**](https://github.com/datatogether/datatogether/blob/master/guidelines/roundtable.md#how-to-host) (and add any improvements!)_

**Comment by dcwalk** [comment]
Hey @jessogden does March 26, 2018 work to host this?

**Comment by weatherpattern** [comment]
Some quick thoughts: (and I missed the initial discussion which lead to the roundtable, so if  this is not what we're talking about, please alter as needed.)

- What do we want to or will we archive?
html, images, pdfs, .xlsx, .txt, .csv, binary?
ie. what web-mon saves versus NOAA weather data?

- What (if any) kinds of data sets we are interested in that are not web-based?

- What (if any) kinds of web content we are not interested in archiving?

**Comment by dcwalk** [comment]
Closing because this happened!
