### ISSUE TITLE
Site certificate is expired

### ISSUE THREAD

**Issue by QuLogic** [datatogether/datatogether#64]
[SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=datatogether.org&hideResults=on) says you have three addresses, but only two have a renewed LE cert.

**Comment by dcwalk** [comment]
Thanks for the catch! Hey @b5 -- I think this is something you have to address?

**Comment by lgierth** [comment]
Oh, mmh, I think this might be a glitch on my end - sorry. Will look into it asap.

**Comment by lgierth** [comment]
Hey, this is fixed now -- mistake on my part while switching the ipfs.io gateways to a new BGP Anycast based setup. (It should be much faster in the US and Asia now.)

**Comment by b5** [comment]
Thanks so much @lgierth for the fix and @QuLogic for pointing this out!
