### ISSUE TITLE
Add Google Group to readme

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#75]
If people want to get periodic email announcements they can request to join the public google group: https://groups.google.com/forum/#!forum/datatogether/join

We should make that clear in this readme (and eventually the website)

**Comment by anand371** [comment]
this is my first time to git could i get this assigned

**Comment by AnkitMArtin** [comment]
@dcwalkI want to work on this issue. But I am a little bit confused  in which section to add them( the google group link )

**Comment by lightandluck** [comment]
@AnkitMArtin I think the `Get Involved` section would be a good place to put the link =)

**Comment by AnkitMArtin** [comment]
@dcwalk I have submitted the changes in the readme(https://github.com/AnkitMArtin/datatogether/tree/24dc507e85905a6139404b2cf1c619ad0fad4d1b) .md. Kindly Pls review it. I will update in website

**Comment by lightandluck** [comment]
Hi @AnkitMArtin, please create a pull request in this repo, not in your fork. We'll be able to review and merge it then.
Thanks!

**Comment by AnkitMArtin** [comment]
Ok

**Comment by AnkitMArtin** [comment]
@lightandluck  Can I have authorized access to add group link in the "datatogether/website" ??

**Comment by lightandluck** [comment]
@AnkitMArtin We have an automated deploy process for pushing up the website, so it's not done manually and we can't give away access to that. We're also in the process of updating the website, so please disregard that part of this issue. 

Thanks so much for submitting your other PR!

**Comment by lightandluck** [comment]
Fixed in [fa7ae20c1](https://github.com/datatogether/datatogether/pull/76/commits/fa7ae20c1ec49a86027d65b5fbbf512567465212).
