### ISSUE TITLE
Archive Repos

### ISSUE THREAD

**Issue by lightandluck** [datatogether/datatogether#79]
Using this as a tracking issue for a bunch of repos we should archive. Gonna go with the advice at DT Annual Meeting in New York (Oct. 2019) and archive any repo that isn't pinned to the main page, excepting any that seem to need more discussion.

Keeping this list so we know which ones were archived in case we need to go back and revert anything. (Will be updating as I go through)

- [x] https://github.com/datatogether/rewrite
- [x] https://github.com/datatogether/sql_util
- [x] https://github.com/datatogether/archive
- [x] https://github.com/datatogether/dt
- [x] https://github.com/datatogether/cdxj
- [x] https://github.com/datatogether/OS_deployment
- [x] https://github.com/datatogether/warc
- [x] https://github.com/datatogether/pdf
- [x] https://github.com/datatogether/xmp

---
These seem to need more discussion. They all revolve around http://archivers.co
- [x] https://github.com/datatogether/webapp
- [x] https://github.com/datatogether/api
- [x] https://github.com/datatogether/coverage
- [x] https://github.com/datatogether/patchbay

---
This repo is a good overview of DT 2017 and how to break down all the repos
- [x] https://github.com/datatogether/roadmap

---
Various libraries

- [x] https://github.com/datatogether/ffi
- [x] https://github.com/datatogether/resources
- [x] https://github.com/datatogether/task_mgmt
- [x] https://github.com/datatogether/sql_datastore

- [x] https://github.com/datatogether/core
- [x] https://github.com/datatogether/extract_href
- [x] https://github.com/datatogether/content
- [x] https://github.com/datatogether/learning
- [x] https://github.com/datatogether/linked_data
- [x] https://github.com/datatogether/identity
- [x] https://github.com/datatogether/dataset_registries
- [x] https://github.com/datatogether/config
- [x] https://github.com/datatogether/memgator

**Comment by b5** [comment]
I think all the archivers.co ones can be archived as well

**Comment by lightandluck** [comment]
Thanks, Brendan! Will do!

**Comment by lightandluck** [comment]
Went through and archived everything on the list. Didn't respond and close every "ok to close" issue, because it didn't seem worth the time. Just went ahead and archived the repos. Feel free to unarchive anything I did by mistake

/cc @Frijol

**Comment by Frijol** [comment]
Thank you!
