### ISSUE TITLE
Privacy of user information on Data Together

### ISSUE THREAD

**Issue by dcwalk** [datatogether/datatogether#9]
From @mhucka in https://github.com/datatogether/learning/issues/22:

> If someone signs up on archivers.co, there is currently no explanation of a privacy and security policy. We should probably have one.
>
> There are probably plenty of starting points. Here's one I wrote for something else, to give us some ideas about the topics that probably should be discussed: http://sbml.org/Facilities/Documentation/Privacy_notice_and_terms_of_service_for_the_Online_SBML_Validator
>
> Also, such things typically need to be vetted by lawyers (or at least that's a requirement whenever I put up an online service at my institution – might be different in this context).

**Comment by dcwalk** [comment]
I'll also second this and say we should, even preliminarily get something up. I'm more used to writing for a Canadian context and additionally research-guided projects (e.g. https://www.ixmaps.ca/privacy.php)

**Comment by mhucka** [comment]
Putting up something short for the short term is a great idea. 

I'm afraid I can't volunteer to do more on this front for the next few weeks but could get involved again in another month.

**Comment by dcwalk** [comment]
I'm going to close this issue/question as it doesn't apply to current questions given the shift in whether or how DT operates as a more or less technical project.

Feel free to re-open if you think my action was premature!
